#!/bin/sh

# file: mkkb.sh
# project: wikidata2
# author: Pavel Raur (xraurp00@stud.fit.vutbr.cz)
# description: merges separate type files into KB

project_folder="$(readlink -f $0 | xargs -I{} dirname {})"
artist_file="$project_folder"/output/artist_merged.tsv
group_file="$project_folder"/output/group_merged.tsv
geographical_file="$project_folder"/output/geographical_merged.tsv
person_file="$project_folder"/output/person_merged.tsv

output_file="$project_folder"/output/KB.tsv

if [ "$1" = "--help" ]; then
	echo 'Description:'
	echo 'Merges files generated by merging wikidata and wikipedia'
	echo 'into single KB.'
	exit 0
fi

echo 'Merging output files into KB'

echo "VERSION=cs_wd+wp_$(date '+%Y%m%d_%H%M%S')" > "$output_file"
cat "$project_folder"/HEAD "$person_file" "$group_file" "$artist_file" "$geographical_file" \
>> "$output_file"

